### ISSUE TITLE
TypeError: 'Series' objects are mutable, thus they cannot be hashed

### ISSUE THREAD

**Issue by NarenInD** [3778/icd-prediction-mimic#5]
@dsevero @arthurreys 
I get `TypeError: 'Series' objects are mutable, thus they cannot be hashed` when running **MIMIC_train_w2v.py** 

Attaching the traceback
```
Traceback (most recent call last):
  File "MIMIC_train_w2v.py", line 56, in <module>
    main(args)
  File "MIMIC_train_w2v.py", line 26, in main
    mimic.split()
  File "C:\Users\kiran\Music\icd-prediction-mimic-master\datasets.py", line 83, in split
    self.all_icds_train = utils.make_icds_histogram(self.df.query("HADM_ID.isin(@hadm_ids[0])")).index.tolist()
  File "C:\Users\kiran\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3184, in query
    res = self.eval(expr, **kwargs)
  File "C:\Users\kiran\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3300, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "C:\Users\kiran\Anaconda3\lib\site-packages\pandas\core\computation\eval.py", line 327, in eval
    ret = eng_inst.evaluate()
  File "C:\Users\kiran\Anaconda3\lib\site-packages\pandas\core\computation\engines.py", line 70, in evaluate
    res = self._evaluate()
  File "C:\Users\kiran\Anaconda3\lib\site-packages\pandas\core\computation\engines.py", line 118, in _evaluate
    _check_ne_builtin_clash(self.expr)
  File "C:\Users\kiran\Anaconda3\lib\site-packages\pandas\core\computation\engines.py", line 27, in _check_ne_builtin_clash
    names = expr.names
  File "C:\Users\kiran\Anaconda3\lib\site-packages\pandas\core\computation\expr.py", line 850, in names
    return frozenset([self.terms.name])
  File "C:\Users\kiran\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1886, in __hash__
    " hashed".format(self.__class__.__name__)
TypeError: 'Series' objects are mutable, thus they cannot be hashed
```

**Comment by dsevero** [comment]
Hi, @NarenInD. Thanks for reaching out.

Judging from the error message, it might be an issue with the version of pandas. Would you mind telling us what version you are using? You can check it by running `import pandas; print(pandas.__version__)` in the python interpreter.

@arthurreys it might be safer to replace

```python
df.query("HADM_ID.isin(@hadm_ids[0])")
```

with

```python
df[df['HADM_ID'].isin(hadm_ids[0])]
```

@NarenInD you can also try the above to see if it helps.

**Comment by NarenInD** [comment]
@dsevero 

The pandas version is **0.25.3**

Also , I replaced the following line as you suggested, but didn't work.

`self.all_icds_train = utils.make_icds_histogram(self.df.query("HADM_ID.isin(@hadm_ids[0])")).index.tolist()`

`self.all_icds_train = utils.make_icds_histogram(self.df[df['HADM_ID'].isin(hadm_ids[0])]).index.tolist()`


The same issues also gets arised in this line of **dataset.py**

```
((self.x_train, self.y_train),
         (self.x_val, self.y_val),
         (self.x_test, self.y_test)) = [
             (self.df.query("HADM_ID.isin(@ids)").TEXT, 
             self.mlb.transform(self.df.query("HADM_ID.isin(@ids)").ICD9_CODE))
             for ids in hadm_ids
             ]
```

**Comment by dsevero** [comment]
@NarenInD, in the first case it should be:

```python
self.df[self.df['HADM_ID'].isin(hadm_ids[0])]
```

in the second, use this:

```python
((self.x_train, self.y_train),
         (self.x_val, self.y_val),
         (self.x_test, self.y_test)) = [
             (self.df[self.df['HADM_ID'].isin(ids)].TEXT, 
             self.mlb.transform(self.df[self.df['HADM_ID'].isin(ids)].ICD9_CODE))
             for ids in hadm_ids
             ]
```

**Comment by arthurreys** [comment]
Hello @NarenInD! 

I've created a new branch [issue-5](https://github.com/3778/icd-prediction-mimic/tree/issue-5) and added the suggested changes from @dsevero. You can checkout to that branch in order to test the modifications.

As already stated, you could also try updating your current pandas version.

Please let us know if it works for you!

**Comment by NarenInD** [comment]
Updated pandas 1.1.1 
But I same Type error issue.

After updating the code @dsevero suggested, It works fine.

Thanks

**Comment by dsevero** [comment]
Good to know! If anything else comes up, let us know :)
