### ISSUE TITLE
Receiving a RuntimeError "you must first build vocabulary before training the model"

### ISSUE THREAD

**Issue by PaigeDavid** [3778/icd-prediction-mimic#7]
When trying to run the MIMIC_train_w2v.py script, I am receiving the RuntimeError listed at the top. One change I made into the code was changing "size" to "vector_size" on line 75 in the feature_extraction.py do to an error of it not recognizing the "size" argument. Unsure if those are related. Full traceback of the error is below:

*Edit: Looks like size has been updated to vector_size. So, that is just a simple fix. However, I have not found a solution for the vocab not being built.*

`Traceback (most recent call last):
  File "C:\Users\paige\Desktop\690 Project\icd-prediction-mimic-master\icd-prediction-mimic-master\MIMIC_train_w2v.py", line 56, in <module>
    main(args)
  File "C:\Users\paige\Desktop\690 Project\icd-prediction-mimic-master\icd-prediction-mimic-master\MIMIC_train_w2v.py", line 32, in main
    w2v.fit(mimic)
  File "C:\Users\paige\Desktop\690 Project\icd-prediction-mimic-master\icd-prediction-mimic-master\feature_extraction.py", line 111, in fit
    epochs=self.model_w2v.epochs)
  File "C:\Python37\lib\site-packages\gensim\models\word2vec.py", line 1034, in train
    self._check_training_sanity(epochs=epochs, total_examples=total_examples, total_words=total_words)
  File "C:\Python37\lib\site-packages\gensim\models\word2vec.py", line 1524, in _check_training_sanity
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model`

**Comment by arthurreys** [comment]
Hello @PaigeDavid! Can you confirm you're using `gensim` version `3.8.3`?

**Comment by PaigeDavid** [comment]
Doing a conda list gensim I get the following:

` packages in environment at C:\Users\paige\Anaconda3:

Name                    Version                   Build  Channel
gensim                    3.8.3                    pypi_0    pypi`

**Comment by arthurreys** [comment]
[This line](https://github.com/3778/icd-prediction-mimic/blob/fb8dfc3140e6cf690690b04eddc735f4f20612cf/feature_extraction.py#L104) in `feature_extraction.py` builds the vocabulary before calling `Word2Vec.train()`, so this error is unexpected. I'll investigate possible reasons and come back to you, ok?

**Comment by PaigeDavid** [comment]
That was my understanding as well when looking through the code. I don't have a lot of knowledge on this stuff, but everything I was seeing online basically was saying I shouldn't be getting this error.

I will add in that I have now tried this on two separate computers, and after fixing the size to vector_size, I receive the same error on both computers. Windows 10. Thanks for looking into it.

**Comment by arthurreys** [comment]
No problem! Are you sure your conda environment is active? I ask that because the [Gensim 3.8.3 documentation](https://radimrehurek.com/gensim_3.8.3/models/word2vec.html#gensim.models.word2vec.Word2Vec) explicitly sets `size`, not `vector_size` to the Word2Vec constructor. This could indicate you're indeed using another version, which could also explain further errors. Could you check into that? Perhaps try and setup another conda env or use a python venv instead.

**Comment by PaigeDavid** [comment]
Looks like I wasn't in an activated environment. Changed back vector_size to size, but it is still giving that error of the unexpected keyword. Here is my full run and traceback:

'(py35) C:\Users\paige\Desktop\690 Project\icd-prediction-mimic-master\icd-prediction-mimic-master>MIMIC_train_w2v.py
2021-08-02 16:36:16.572323: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-08-02 16:36:16.572426: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Python37\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\paige\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

            Data Split: 0, 0, 0

Traceback (most recent call last):
  File "C:\Users\paige\Desktop\690 Project\icd-prediction-mimic-master\icd-prediction-mimic-master\MIMIC_train_w2v.py", line 56, in <module>
    main(args)
  File "C:\Users\paige\Desktop\690 Project\icd-prediction-mimic-master\icd-prediction-mimic-master\MIMIC_train_w2v.py", line 29, in main
    w2v = fx.W2V(args)
  File "C:\Users\paige\Desktop\690 Project\icd-prediction-mimic-master\icd-prediction-mimic-master\feature_extraction.py", line 76, in __init__
    workers=self.args.workers, sg=self.args.sg, seed=3778)
TypeError: __init__() got an unexpected keyword argument 'size''

**Comment by arthurreys** [comment]
Ok, so the problem seems to be something else. One last try regarding versions, just to be sure. Could you please create a .py file with these contents and run it inside your environment and show us the printed message?

```
import numpy
import gensim
import pandas

print(numpy.__version__, gensim.__version__, pandas.__version__)
```

It's also unexpected to see `Data Split: 0, 0, 0` in your log. Have you followed steps 1 and 2 from the `README.md`? I've had this issue before when using a newer version of pandas. You should've gotten  `Data Split: 47719, 1631, 3372` instead.

**Comment by PaigeDavid** [comment]
I did do steps 1 and 2, and I made sure I did them in the activated environment. Unsure if that mattered.

Results from running the python file:

C:\Python37\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
1.19.2 4.0.1 1.3.1

(py35) C:\Users\paige\Desktop\690 Project\icd-prediction-mimic-master\icd-prediction-mimic-master>python --version
Python 3.6.9 :: Anaconda, Inc.

I ran python --version just to make sure since it looks like python 3.7 is being called? But I am not sure, nor am, I sure how I would change that in the conda environment

**Comment by arthurreys** [comment]
Looks like you're using version 4.0.1 of `gensim` and 1.3.1 of `pandas`. Downgrading them to the versions specified in the README should do the trick. As far as I can see, you seem to have a conda environment named `py35` activated in your terminal. Could you please try and run this code line by line in your terminal?

```
> conda deactivate
> conda create --name icd_mimic python=3.6.9 numpy=1.19.0 scikit-learn=0.23.1 pandas=0.25.3 nltk=3.4.4 scipy=1.4.1 gensim=3.8.3 tensorflow=2.1.0
> conda activate icd_mimic
```
After running the code above sucessfully, you'll be in a new conda env (icd_mimic). Execute your python script (the one which prints the packages' versions) by running `python script_name.py`. If the printed versions are correct (1.19.0 3.8.3 0.25.3), go ahead and run steps 1,2 and 3 from the README again. Let me know if everything worked (:

**Comment by PaigeDavid** [comment]
Yup. that appears to have fixed it. It is currently training embeddings and I got a Data Split of 47719, 1631, 3372. Thank you! Python is not my forte, but this model was perfect for my paper. Thank you for the help and quick responses

**Comment by arthurreys** [comment]
Anytime! Good luck in your research!

**Comment by arthurreys** [comment]
I'm closing this issue as we have solved it. Feel free to open it again or contact me via email if any new questions arise.
