### ISSUE TITLE
ValueError when running MIMIC_train_w2v.py file. 

### ISSUE THREAD

**Issue by Mercapto13** [3778/icd-prediction-mimic#8]
self.embedding_matrix = np.concatenate((self.embedding_matrix, np.zeros((2,W2V_SIZE))), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 100 and the array at index 1 has size 300

**Comment by arthurreys** [comment]
Hey @Mercapto13, thanks for reaching out!

It seems that your trained word2vec embedding matrix has size 100, but when you reach [this point](https://github.com/3778/icd-prediction-mimic/blob/fb8dfc3140e6cf690690b04eddc735f4f20612cf/feature_extraction.py#L126) it tries to concatenate the embedding matrix with a larger array (along dimension 1).

The dimension 1 sizes in this concatenation should match, as the [Word2Vec class](https://github.com/3778/icd-prediction-mimic/blob/fb8dfc3140e6cf690690b04eddc735f4f20612cf/feature_extraction.py#L75) and the concatenation array are instantiated with the same `W2V_SIZE` integer.

If you're loading an already trained embedding model, then you should change W2V_SIZE to match its size (in this case, change to 100). If not, can you please tell me if you've modified the code in any way, so we can further investigate the issue?

**Comment by Mercapto13** [comment]
The issue is fixed now. I removed a line from the code by mistake. Thank you for your prompt reply.
